### ISSUE TITLE
Images in my clipboard won't transfer.

### ISSUE THREAD

**Issue by VelanTheKind** [soduto/Soduto#23]
I have my screenshot settings on my mac set so that the most recent screenshot I have taken is saved to my clipboard. I am not able to paste the screenshots into the notes that I am taking on my tablet. Text transfers fine but the images won't transfer. Dragging the screenshot into the Soduto icon in the menu bar transfers the file to the tablet but I have to find its location in my files and then copy the image into my clipboard. If there was a way to streamline this process so that the image is immediately added to my clipboard, I would appreciate it. 

I attempted to take a look at the Xcode for Soduto hoping for a Quick fix but it isn't something that I can easily navigate. I have more experience developing for android. A side app that recognizes that an image has been downloaded to a folder and then adds that image to a clipboard should be possible.

**Comment by giedrius-stanevicius** [comment]
Soduto is only intended to handle the macOS side of interactions, so a side app for Android would be out of scope of this project. 
At the time clipboard sharing feature was implemented KDE Connect would only support text sharing - that's why it does not support images. I wonder whether things had changed on KDE Connect side since then. If KDE Connect now support image sharing via clipboard, it should not be difficult to implement such feature on Soduto too.
