### ISSUE TITLE
network scan

### ISSUE THREAD

**Issue by garaboncias** [soduto/Soduto#4]
soduto scanned my network on 10.0.0.x
What is the reason of this?

**Comment by giedrius-stanevicius** [comment]
Soduto scans some range of local network to find other KDE Connect/Soduto clients. Normally it would not be needed, because clients announce themselves by sending broadcast messages to the network. However there are issues with various mobile devices that don't handle such brodacast messages (especially if they are in sleep mode) and can't be seen by Soduto. Pinging and then sending direct messages for such devices are often handled more reliably, so it is the method we use. But in order to send  direct message, you need to know the IP address of the client, hence the scan.

**Comment by giedrius-stanevicius** [comment]
It looks resolved
